# Generated by Django 4.2.7 on 2024-02-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_membershipplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='price',
            new_name='Price',
        ),
    ]
