# Generated by Django 4.2.7 on 2024-02-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_galle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galle',
            new_name='Gallery',
        ),
    ]
