# Generated by Django 4.2.7 on 2024-02-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Phonenumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
