# Generated by Django 4.2.7 on 2024-02-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_attendance_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
    ]
